(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "CHANGEBASESTRING"
   "<CHANGEBASESTRING-REQUEST>"
   "CHANGEBASESTRING-REQUEST"
   "<CHANGEBASESTRING-RESPONSE>"
   "CHANGEBASESTRING-RESPONSE"
  ))

